global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'go-server'
    static_configs:
      - targets: ['web:8080']

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'
